# -*- coding: utf-8 -*-
"""clase1ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14qbSVrhbIf_bw5JP0C-HfquxhCrgwAyc
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/MyDrive/db'

data=pd.read_csv("diabetes.csv")
data.head()
d=data.dtypes
data

data=data.dropna()
data

f=plt.figure(figsize=(8,4))
ax=f.add_subplot(1,1,1)
data["Outcome"].hist(ax=ax,edgecolor="black",linewidth=2)
ax.set_xlim([-0.5,1.5])
ax.set_xticks([0,1])
ax.set_xticklabels(["N", "Y"])
ax.set_title("Diabetes Y/N?")
ax.set_xlabel("Answer")
ax.set_ylabel("Count")
ax.set_ylim([0, 510])
f.tight_layout()

f=plt.figure(figsize=(8,4))
ax=f.add_subplot(1,1,1)
data["Age"].hist(ax=ax,edgecolor="black",linewidth=2)
ax.set_xlim([0,50])
ax.set_xticks([0,1])
ax.set_xticklabels(["N", "Y"])
ax.set_title("Age range")
ax.set_xlabel("Age")
ax.set_ylabel("Count")
ax.set_ylim([0, 400])
f.tight_layout()

fig=plt.figure(figsize=(18,8))
binvalues=[20,25,30,35,40,85]
colores=["blue","red","green","yellow","magenta","cyan"]
count=0
for i in binvalues:
 ax=fig.add_subplot(2,3,count+1)
 data["Age"].hist(ax=ax,bins=i,edgecolor="black",linewidth=2,color=colores[count])
 count=count+1
 ax.set_title("Age range of patients "+str(i)+" Bins")
 fig.tight_layout()

fig=plt.figure(figsize=(5,5))
ax=fig.add_subplot(1,1,1)
ax.scatter(data["BloodPressure"],data["Age"],alpha=0.45)
ax.set_title("Blood pressure VS Age")
fig.tight_layout()

data=data[data["BloodPressure"]>0]
fig=plt.figure(figsize=(5,5))
ax=fig.add_subplot(1,1,1)
ax.scatter(data["BloodPressure"],data["Age"],alpha=0.45)
ax.set_title("Blood pressure VS Age")
ax.set_xlim([0,150])
fig.tight_layout()

data=data[data["BloodPressure"]>0]
diabetic=data[data["Outcome"]==1]
non_diabetic=data[data["Outcome"]==0]
fig=plt.figure(figsize=(10,10))
ax=fig.add_subplot(1,2,1)
ax.scatter(diabetic["BloodPressure"],diabetic["Age"],alpha=0.45)
ax.set_title("Blood pressure (Diabetics) VS Age")
ax.set_xlim([0,150])
fig.tight_layout()
ax=fig.add_subplot(1,2,2)
ax.scatter(non_diabetic["BloodPressure"],non_diabetic["Age"],alpha=0.45)
ax.set_title("Blood pressure (Non Diabetics) VS Age")
ax.set_xlim([0,150])
fig.tight_layout()